### ISSUE TITLE
Bug: Events With Timestamps Fail For 10 Hours Everyday

### ISSUE THREAD

**Issue by tvanderstad** [polyverse/pagerduty-rs#2]
The serialization code uses the `%T` formatter to print the time to a string in the request, but `%T` does not pad the hour value, resulting in a non-ISO-8601-compliant datetime string and therefore a 400 from PagerDuty's API.

Serialization code here: https://github.com/polyverse/pagerduty-rs/blob/main/src/types.rs#L199
PagerDuty docs on datetime spec: https://developer.pagerduty.com/docs/rest-api-v2/types/#datetime
`time` crate formatting directives: https://docs.rs/time/0.2.26/time/#formatting (note `%T` definition)

Solution is to format the time using this revised version of the serializer function:
```
fn datetime_to_iso8601<S>(d: &OffsetDateTime, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    serializer.serialize_str(d.format("%FT%H:%M:%S.%NZ").as_str())
}
```

**Comment by archisgore** [comment]
Thanks for the suggestion. I'm working on it now.
